
development:
  adapter: postgresql
  encoding: utf8
  database: indurfresh_development
  username: indurfresh
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: indurfresh_test
  username: indurfresh
  password:
  host: localhost